AllCops:
  Excludes:
    - db/schema.rb

# 15 is too low!
Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
